language: python
os: windows
language: shell
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
before_install:
  - choco install python
  - python -m pip3 install -r requirements.txt
  - python requirements/test_server.py
